services:
  db:
    image: postgres:16-alpine
    container_name: reaseau_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-database}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - reaseau_network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-database}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    name: reseau_db_data

networks:
  reaseau_network:
    name: reaseau_network
    driver: bridge
